name: Windows Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: > 
          mingw-w64-x86_64-gcc
          make
    - name: Add MSYS2 to PATH
      run: echo "::add-path::C:/msys64/mingw64/bin"
    - name: Build
      run: |
        make -f Makefile platform=windows
