name: Windows Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
    - name: Install dependencies
      run: |
        pacman -S --noconfirm make mingw-w64-x86_64-gcc
    - name: Build
      run: |
        make -f Makefile platform=windows
